name: wendys_test
description: "A Flutter projet to serve as test for Navalia"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  http: ^1.2.2
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true